# Generated by Django 2.0.1 on 2019-03-03 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190223_2347'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
