# Generated by Django 2.0.1 on 2019-03-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_delete_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='media/image/default/Entity/user_default.png', upload_to='media/image/%Y/%m'),
        ),
    ]
