# Generated by Django 2.0.1 on 2019-03-25 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AffDistribute',
        ),
    ]
